services:
  - type: web
    name: shl-api
    env: python
    buildCommand: "pip install -r requirements.txt && python src/embeddings.py"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"